# Generated by CMakePlugin
.PHONY: all clean $(MAKECMDGOALS)

CMAKE      := "C:\cmake-3.1.0-rc1-win32-x86\bin\cmake.exe"
BUILD_DIR  := ../build
SOURCE_DIR := ../ex1_basic_led
CMAKE_ARGS := -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug

# Building project(s)
$(or $(lastword $(MAKECMDGOALS)), all): $(BUILD_DIR)/Makefile
	$(MAKE) -C "$(BUILD_DIR)" $(MAKECMDGOALS)

# Building directory
$(BUILD_DIR):
	$(CMAKE) -E make_directory "$(BUILD_DIR)"

# Rule that detects if cmake is called
$(BUILD_DIR)/Makefile: .cmake_dirty | $(BUILD_DIR)
	cd "$(BUILD_DIR)" && $(CMAKE) $(CMAKE_ARGS) "$(SOURCE_DIR)"

# This rule / file allows force cmake run
.cmake_dirty:
	@echo '' > .cmake_dirty

