.PHONY: clean All

All:
	@echo "----------Building project:[ ex1_basic_led - Debug ]----------"
	@$(MAKE) -f  "ex1_basic_led.mk"
clean:
	@echo "----------Cleaning project:[ ex1_basic_led - Debug ]----------"
	@$(MAKE) -f  "ex1_basic_led.mk" clean
